// Ordinary headless checks of GENERATED fixtures. These are not manual UI QA.
import { readFileSync } from 'node:fs';
import { test } from 'vitest';
import { assemble, interpret, type ReferenceRun } from '../../scripts/original_cpu/reference';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import '../engine/index';
import { loadCircuit } from '../engine/loader';
import { Simulator } from '../engine/sim';
import type { CircuitJSON, NetState } from '../engine/ir';
import reference from '../../examples/original_digital_cpu_generated.json';
const faithful = reference as unknown as CircuitJSON;
const manual = structuredClone(faithful);
for (const component of manual.components) {
  if (component.type === 'gen.clock') {
    component.type = 'io.switch';
    delete component.params;
  }
}
const definitions = manual.definitions!;
const byName = new Map(definitions.map((definition) => [definition.name, definition]));
const programs: Record<string, ReferenceRun> = {};
for (const name of ['callret', 'countdown', 'fib', 'pushpop']) {
  const file = fileURLToPath(new URL(`../../scripts/original_cpu/programs/${name}.asm`, import.meta.url));
  programs[name] = interpret(assemble(readFileSync(file, 'utf8')));
}
function wrap(name: string): Simulator {
  const d = byName.get(name)!;
  if (!d)
    throw new Error('Unknown definition ' + name);
  const closure = new Map<string, CircuitJSON>();
  function add(n: string): void {
    if (closure.has(n)) return;
    const def = byName.get(n);
    if (!def) return;
    closure.set(n, def);
    for (const c of def.components) add(c.type);
  }
  add(name);
  const obj: CircuitJSON = { version: 1, kind: 'circuit', name: 'Generated test harness for ' + name, components: [{ id: 'U', type: name }], nets: d.ports!.map(p => ({ id: p.name, endpoints: [`U.${p.name}`] })), definitions: [...closure.values()] };
  const sim = new Simulator(loadCircuit(obj));
  for (const p of d.ports!)
    if (p.dir === 'in')
      sim.setInput(p.name, 0);
  sim.settle();
  return sim;
}
function set(sim: Simulator, pin: string, value: NetState) { sim.setInput(pin, value); }
function word(sim: Simulator, label: string, width: number, value: number): void {
  for (let i = 0; i < width; i++) {
    set(sim, width === 1 ? label : `${label}_${i}`, ((value >>> i) & 1) as NetState);
  }
}
function read(sim: Simulator, label: string, width: number): number | string {
  let value = 0;
  for (let i = 0; i < width; i++) {
    const n = sim.readNet(width === 1 ? label : `${label}_${i}`);
    if (n !== 0 && n !== 1)
      return String(n);
    value += n * 2 ** i;
  }
  return value;
}
function edge(sim: Simulator, clk: string = 'C'): void {
  set(sim, clk, 0); sim.settle();
  set(sim, clk, 1); sim.settle();
}
function quiet(sim: Simulator) { assert(!sim.events.some(e => e.kind === 'oscillation'), 'Oscillation emitted'); }
test('Converted circuit and derived clock harness retain original hierarchy', () => {
  const a = loadCircuit(faithful), b = loadCircuit(manual);
  assert.equal(faithful.components.find(c => c.id === 'v2')!.type, 'gen.clock');
  assert.equal(faithful.components.find(c => c.id === 'v84')!.type, 'gen.clock');
  assert.equal(manual.components.find(c => c.id === 'v2')!.type, 'io.switch');
  const sourceDefs = definitions.filter(d => String(d.metadata?.source_file ?? '').endsWith('.dig') || String(d.metadata?.source_file ?? '').endsWith('.dist'));
  assert.equal(sourceDefs.length, 9);
  assert.equal(definitions.length, 25);
  assert.equal(a.components.length, b.components.length);
  assert.equal(a.nets.length, b.nets.length);
  const bootImage = String(faithful.components.find((component) => component.id === 'v82')!.params!.contents)
    .replace('v2.0 raw', '').trim().split(/\s+/).map((word) => Number.parseInt(word, 16));
  assert.deepEqual(bootImage, programs.callret!.program_bytes);
});
test('Original one-bit feedback register load and hold', () => {
  const s = wrap('user.Digital_1_bit_reg');
  set(s, 'Clk', 0);
  set(s, 'Load', 1);
  set(s, 'D', 1);
  s.settle();
  assert.equal(read(s, 'Q', 1), 0);
  edge(s, 'Clk');
  assert.equal(read(s, 'Q', 1), 1);
  set(s, 'Load', 0);
  set(s, 'D', 0);
  edge(s, 'Clk');
  assert.equal(read(s, 'Q', 1), 1);
  set(s, 'Load', 1);
  edge(s, 'Clk');
  assert.equal(read(s, 'Q', 1), 0);
  quiet(s);
});
test('Generated byte Register primitive equivalent rising edge / enable', () => {
  const s = wrap('user.DigitalLeaf_Register_8');
  word(s, 'D', 8, 0xa5);
  set(s, 'en', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 0);
  edge(s);
  assert.equal(read(s, 'Q', 8), 0xa5);
  word(s, 'D', 8, 0x5a);
  set(s, 'en', 0);
  edge(s);
  assert.equal(read(s, 'Q', 8), 0xa5);
  set(s, 'en', 1);
  edge(s);
  assert.equal(read(s, 'Q', 8), 0x5a);
  quiet(s);
});
test('Converted register captures data changed with its rising clock', () => {
  const s = wrap('user.DigitalLeaf_Register_8');
  set(s, 'en', 1);
  s.settle();
  word(s, 'D', 8, 1);
  set(s, 'C', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 1);
  word(s, 'D', 8, 3);
  s.settle();
  assert.equal(read(s, 'Q', 8), 1, 'data changes while clock is HIGH must hold');
  set(s, 'C', 0);
  s.settle();
  set(s, 'en', 0);
  set(s, 'C', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 1, 'enable is sampled on the edge');
  quiet(s);
});
test('Converted CounterPreset captures load data changed with its rising clock', () => {
  const s = wrap('user.DigitalLeaf_CounterPreset_8');
  set(s, 'ld', 1);
  word(s, 'in', 8, 1);
  s.settle();
  word(s, 'in', 8, 3);
  set(s, 'C', 1);
  s.settle();
  assert.equal(read(s, 'out', 8), 3);
  set(s, 'C', 0);
  s.settle();
  set(s, 'clr', 1);
  set(s, 'C', 1);
  s.settle();
  assert.equal(read(s, 'out', 8), 0, 'clear changed with the edge beats load');
  quiet(s);
});
test.each(['Counter_5', 'CounterPreset_8'])('Converted %s samples enable changed with its rising clock', (kind) => {
  const width = kind === 'Counter_5' ? 5 : 8;
  const s = wrap('user.DigitalLeaf_' + kind);
  set(s, 'en', 1);
  set(s, 'C', 1);
  s.settle();
  assert.equal(read(s, 'out', width), 1);
  if (kind === 'CounterPreset_8') {
    set(s, 'C', 0);
    s.settle();
    set(s, 'dir', 1);
    set(s, 'C', 1);
    s.settle();
    assert.equal(read(s, 'out', width), 0, 'direction is sampled on the edge');
    assert.equal(read(s, 'ovf', 1), 1);
  }
  quiet(s);
});
test('Counter synchronous clear / hold / wrap', () => {
  const s = wrap('user.DigitalLeaf_Counter_5');
  set(s, 'en', 1);
  for (let i = 1; i <= 32; i++) {
    edge(s);
    assert.equal(read(s, 'out', 5), i & 31);
    assert.equal(read(s, 'ovf', 1), (i & 31) === 31 ? 1 : 0);
  }
  set(s, 'en', 0);
  edge(s);
  assert.equal(read(s, 'out', 5), 0);
  set(s, 'en', 1);
  edge(s);
  assert.equal(read(s, 'out', 5), 1);
  set(s, 'clr', 1);
  s.settle();
  assert.equal(read(s, 'out', 5), 1);
  edge(s);
  assert.equal(read(s, 'out', 5), 0);
  quiet(s);
});
test('CounterPreset clear > load > enabled increment and descending wrap', () => {
  const s = wrap('user.DigitalLeaf_CounterPreset_8');
  set(s, 'en', 1);
  set(s, 'ld', 1);
  word(s, 'in', 8, 77);
  edge(s);
  assert.equal(read(s, 'out', 8), 77);
  set(s, 'clr', 1);
  word(s, 'in', 8, 88);
  edge(s);
  assert.equal(read(s, 'out', 8), 0);
  set(s, 'clr', 0);
  set(s, 'ld', 0);
  set(s, 'dir', 1);
  edge(s);
  assert.equal(read(s, 'out', 8), 255);
  set(s, 'dir', 0);
  edge(s);
  assert.equal(read(s, 'out', 8), 0);
  set(s, 'en', 0);
  set(s, 'ld', 1);
  word(s, 'in', 8, 13);
  edge(s);
  assert.equal(read(s, 'out', 8), 13);
  quiet(s);
});
test('8-bit add/sub equivalents sampled arithmetic and borrow', () => {
  const a = wrap('user.DigitalLeaf_Add_8'), b = wrap('user.DigitalLeaf_Sub_8');
  for (let x = 0; x < 256; x++)
    for (const y of [0, 1, 127, 128, 255])
      for (const c of [0, 1]) {
        word(a, 'a', 8, x);
        word(a, 'b', 8, y);
        set(a, 'c_i', c as NetState);
        a.settle();
        assert.equal(read(a, 's', 8), (x + y + c) & 255);
        assert.equal(read(a, 'c_o', 1), x + y + c > 255 ? 1 : 0);
        word(b, 'a', 8, x);
        word(b, 'b', 8, y);
        set(b, 'c_i', c as NetState);
        b.settle();
        assert.equal(read(b, 's', 8), (x - y - c) & 255);
        assert.equal(read(b, 'c_o', 1), x - y - c < 0 ? 1 : 0);
      }
  quiet(a);
  quiet(b);
});
test('Unsigned comparator across sign boundary / equality', () => {
  const s = wrap('user.DigitalLeaf_Comparator_8');
  for (let a = 0; a < 256; a++)
    for (const b of [0, 1, 127, 128, 255, a]) {
      word(s, 'a', 8, a);
      word(s, 'b', 8, b);
      s.settle();
      assert.equal(read(s, 'GT', 1), a > b ? 1 : 0);
      assert.equal(read(s, 'EQ', 1), a === b ? 1 : 0);
      assert.equal(read(s, 'LT', 1), a < b ? 1 : 0);
    }
  quiet(s);
});
test('Original ALU input/output bit order and comparator outputs', () => {
  const s = wrap('user.Digital_ALU');
  for (const a of [0, 1, 127, 128, 255])
    for (const b of [0, 1, 127, 128, 255])
      for (const sub of [0, 1]) {
        for (let i = 0; i < 8; i++) {
          set(s, `A${i}`, ((a >>> i) & 1) as NetState);
          set(s, `B${i}`, ((b >>> i) & 1) as NetState);
        }
        set(s, 'Sub', sub as NetState);
        s.settle();
        let out = 0;
        for (let i = 0; i < 8; i++)
          out += Number(s.readNet(`O${i}`)) * 2 ** i;
        assert.equal(out, (a + (sub ? -b : b)) & 255);
        assert.equal(read(s, 'AEq', 1), a === b ? 1 : 0);
        assert.equal(read(s, 'AGreater', 1), a > b ? 1 : 0);
        assert.equal(read(s, 'AZero', 1), a === 0 ? 1 : 0);
      }
  quiet(s);
});
test('Mux eight routes and 4-way write demux', () => {
  const m = wrap('user.DigitalLeaf_Mux_8_3'), d = wrap('user.DigitalLeaf_Demux_1_2');
  for (let i = 0; i < 8; i++)
    word(m, `in${i}`, 8, 17 + i * 13);
  for (let i = 0; i < 8; i++) {
    word(m, 'sel', 3, i);
    m.settle();
    assert.equal(read(m, 'out', 8), 17 + i * 13);
  }
  set(d, 'in', 1);
  for (let i = 0; i < 4; i++) {
    word(d, 'sel', 2, i);
    d.settle();
    for (let j = 0; j < 4; j++)
      assert.equal(read(d, `out${j}`, 1), i === j ? 1 : 0);
  }
  quiet(m);
  quiet(d);
});
test('Original 32-byte RAM all words, read disabled, writes independent of read enable', () => {
  const s = wrap('user.Digital_32_byte_ram');
  set(s, 'En', 0);
  set(s, 'Wr', 1);
  for (let i = 0; i < 32; i++) {
    word(s, 'Addr', 5, i);
    word(s, 'Bus', 8, (i * 7 + 3) & 255);
    edge(s, 'Clk');
  }
  assert.equal(read(s, 'Out', 8), 'Z');
  set(s, 'Wr', 0);
  set(s, 'En', 1);
  for (let i = 0; i < 32; i++) {
    word(s, 'Addr', 5, i);
    s.settle();
    assert.equal(read(s, 'Out', 8), (i * 7 + 3) & 255);
  }
  set(s, 'En', 0);
  s.settle();
  assert.equal(read(s, 'Out', 8), 'Z');
  quiet(s);
});
test('Original stack initialization / reset / look-ahead / load', () => {
  const s = wrap('user.Digital_stack_register');
  edge(s, 'Clk');
  assert.equal(read(s, 'Q', 8), 255);
  set(s, 'Dec', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 254);
  word(s, 'D', 8, 254);
  set(s, 'Ld', 1);
  edge(s, 'Clk');
  set(s, 'Dec', 0);
  set(s, 'Ld', 0);
  s.settle();
  assert.equal(read(s, 'Q', 8), 254);
  set(s, 'Inc', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 255);
  set(s, 'Dec', 1);
  s.settle();
  assert.equal(read(s, 'Q', 8), 0);
  set(s, 'Inc', 0);
  set(s, 'Dec', 0);
  set(s, 'Rst', 1);
  edge(s, 'Clk');
  set(s, 'Rst', 0);
  s.settle();
  assert.equal(read(s, 'Q', 8), 255);
  quiet(s);
});
// Read source-derived logical root pins without depending on incidental lane IDs.
type PinMap = {
  element: number;
  source_pin: string;
  source_bit: number;
  bread_net: string;
};
const rootPins = new Map((manual.metadata!.pin_map as PinMap[]).filter((pin) => pin.bread_net)
  .map((pin) => [`${pin.element}.${pin.source_pin}.${pin.source_bit}`, pin.bread_net]));
function rootNet(element: number, pin: string, bit = 0): string {
  const net = rootPins.get(`${element}.${pin}.${bit}`);
  if (!net)
    throw new Error(`Missing root source pin ${element}.${pin}[${bit}]`);
  return net;
}
function rootWord(s: Simulator, element: number, pin: string, width: number): number | string {
  let value = 0;
  for (let bit = 0; bit < width; bit++) {
    const n = s.readNet(rootNet(element, pin, bit));
    if (n !== 0 && n !== 1) return String(n);
    value += n * 2 ** bit;
  }
  return value;
}
function rootReg(s: Simulator, element: number): number | string {
  let value = 0;
  for (let bit = 0; bit < 8; bit++) {
    const n = s.readNet(rootNet(element, `Q${bit}`));
    if (n !== 0 && n !== 1) return String(n);
    value += n * 2 ** bit;
  }
  return value;
}
function snapshot(s: Simulator) {
  return {
    PC: rootWord(s, 20, 'out', 8), A: rootReg(s, 0), B: rootReg(s, 1),
    IR: rootReg(s, 7), MAR: rootReg(s, 29), OUT: rootReg(s, 34),
    SP: rootWord(s, 117, 'Q', 8), Rdy: s.readNet(rootNet(83, 'ovf')),
    boot: rootWord(s, 83, 'out', 5), Hlt: s.readNet(rootNet(68, 'Hlt')),
    RstDone: s.readNet(rootNet(68, 'RstDone')), cpuClock: s.readNet(rootNet(20, 'C')),
  };
}
function runtimePin(s: Simulator, id: string, pin: string): NetState {
  const component = s.graph.components[s.graph.componentById.get(id)!];
  if (!component)
    throw new Error('Missing runtime component ' + id);
  const index = component.pins.findIndex(p => p.name === pin);
  if (index < 0)
    throw new Error(`Missing runtime pin ${id}.${pin}`);
  return s.graph.nets[component.pinNetIdx[index]!]!.value;
}
function runtimeWord(s: Simulator, id: string, label: string, width: number): number | string {
  let value = 0;
  for (let i = 0; i < width; i++) {
    const n = runtimePin(s, id, label + i);
    if (n !== 0 && n !== 1)
      return String(n);
    value += n * 2 ** i;
  }
  return value;
}
function mpc(s: Simulator): number | string {
  let value = 0;
  for (let i = 0; i < 3; i++) {
    const n = runtimePin(s, 'v68__v20__counter', `Q${i}`);
    if (n !== 0 && n !== 1)
      return String(n);
    value += n * 2 ** i;
  }
  return value;
}
function memory(s: Simulator): Array<number | string> {
  const regs = [0, 5, 6, 7, 8, 9, 10, 11], words: Array<number | string> = [];
  for (let bank = 0; bank < 4; bank++)
    for (const reg of regs) {
      let value = 0, unknown: string | undefined;
      for (let bit = 0; bit < 8; bit++) {
        const n = runtimePin(s, `v31__v${bank}__v${reg}__bit${bit}`, 'Q');
        if (n !== 0 && n !== 1)
          unknown = String(n);
        else
          value += n * 2 ** bit;
      }
      words.push(unknown ?? value);
    }
  return words;
}
function architecture(s: Simulator) {
  const basic = snapshot(s), flag = rootReg(s, 94);
  return {
    ...basic, MPC: mpc(s), ram: memory(s),
    flags: typeof flag === 'number' ? { eq: Boolean(flag & 4), greater: Boolean(flag & 2), zero: Boolean(flag & 1) } : flag,
  };
}
function stable(s: Simulator) {
  const state = snapshot(s);
  const unknown = Object.entries(state).filter(([, value]) => value === 'X' || value === 'Z');
  const bus = Array.from({ length: 8 }, (_, bit) => s.readNet(rootNet(20, 'in', bit)));
  const contention = s.graph.nets.filter(n => n.value === 'X' && n.drivers.some(d => s.graph.components[d.comp]!.outputBuf[d.outIdx] === 0) && n.drivers.some(d => s.graph.components[d.comp]!.outputBuf[d.outIdx] === 1)).map(n => n.id);
  return { architectural_unknowns: unknown, bus, stable_contention: contention };
}
type ExpectedProgram = ReferenceRun;
function runProgram(program: ExpectedProgram, resetBeforeBoot = false) {
  const fixture = structuredClone(manual);
  const rom = fixture.components.find(c => c.id === 'v82')!;
  rom.params!.contents = 'v2.0 raw\n' + program.program_bytes.map(v => v.toString(16)).join('\n');
  const s = new Simulator(loadCircuit(fixture));
  s.settle();
  const initial = { ...architecture(s), stable: stable(s) };
  if (resetBeforeBoot) {
    s.setComponentInput('v116', 'Y', 1);
    s.settle();
    s.setComponentInput('v116', 'Y', 0);
    s.settle();
  }
  const phases: Array<Record<string, unknown>> = [], boundaries: Array<Record<string, unknown>> = [], outputs: number[] = [];
  let halted = false;
  let bootPulses = 0;
  let cpuPulses = 0;
  for (let cycle = 0; cycle < 3000; cycle++) {
    if (s.readNet(rootNet(83, 'ovf')) === 0) {
      s.setComponentInput('v84', 'Y', 1);
      s.settle();
      bootPulses++;
      s.setComponentInput('v84', 'Y', 0);
      s.settle();
      phases.push({ cycle, phase: 'boot', ...architecture(s), stable: stable(s) });
      continue;
    }
    const controls = runtimeWord(s, 'v68__v0', 'D', 29);
    const ldOut = s.readNet(rootNet(68, 'LdOut'));
    const previousClock = s.readNet(rootNet(20, 'C'));
    s.setComponentInput('v2', 'Y', 1);
    s.settle();
    cpuPulses++;
    const after = architecture(s);
    const status = stable(s);
    phases.push({ cycle, phase: 'primary-high', control_word: controls, ...after, stable: status });
    assert.equal(status.architectural_unknowns.length, 0);
    assert.equal(status.stable_contention.length, 0);
    if (previousClock === 0 && after.cpuClock === 1 && ldOut === 1) {
      assert.equal(typeof after.OUT, 'number');
      outputs.push(after.OUT as number);
    }
    if (typeof controls === 'number' && (controls & (2 ** 20)) !== 0 && after.cpuClock === 1)
      boundaries.push({ cycle, ...after });
    s.setComponentInput('v2', 'Y', 0);
    s.settle();
    const low = architecture(s), lowStatus = stable(s);
    phases.push({ cycle, phase: 'primary-low', ...low, stable: lowStatus });
    assert.equal(lowStatus.architectural_unknowns.length, 0);
    assert.equal(lowStatus.stable_contention.length, 0);
    if (low.Hlt === 1) {
      boundaries.push({ cycle, ...low });
      halted = true;
      break;
    }
  }
  assert(halted, `CPU did not halt in bounded test: ${JSON.stringify(architecture(s))}`);
  quiet(s);
  return { s, initial, final: architecture(s), phases, boundaries, outputs, bootPulses, cpuPulses };
}
function compareProgram(run: ReturnType<typeof runProgram>, oracle: ReferenceRun, name: string): void {
  assert.deepEqual(run.outputs, oracle.output_history);
  assert.equal(run.boundaries.length, oracle.instructions.length);
  const fields = [['PC', 'pc'], ['A', 'a'], ['B', 'b'], ['OUT', 'out'], ['SP', 'sp']] as const;
  for (let i = 0; i < run.boundaries.length; i++) {
    const observed = run.boundaries[i]!, expected = oracle.instructions[i]!.after;
    for (const [actual, key] of fields)
      assert.equal(observed[actual], expected[key], `${name}: instruction ${i} ${actual}`);
    assert.deepEqual(observed.flags, expected.flags, `${name}: instruction ${i} flags`);
    assert.deepEqual(observed.ram, expected.ram, `${name}: instruction ${i} RAM`);
    assert.equal(observed.Hlt, Number(expected.halted), `${name}: instruction ${i} halt`);
  }
  // The raw oscillators may keep toggling after HLT; storage must stay fixed.
  const before = architecture(run.s);
  for (let pulse = 0; pulse < 20; pulse++) {
    run.s.setComponentInput('v2', 'Y', 1);
    run.s.settle();
    run.s.setComponentInput('v2', 'Y', 0);
    run.s.settle();
  }
  assert.deepEqual(architecture(run.s), before);
}
const originalOutputs: Record<string, number[]> = {
  callret: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], countdown: [5, 4, 3, 2, 1, 0],
  fib: [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144], pushpop: [42],
};
for (const name of ['callret', 'countdown', 'fib', 'pushpop'])
  test(`Full original ${name} program matches independent ISA at every instruction`, () => {
    const oracle = programs[name]!;
    assert.deepEqual(oracle.output_history, originalOutputs[name]);
    compareProgram(runProgram(oracle), oracle, name);
  });
const probes: Array<{
  name: string;
  code: number[];
  output: number[];
}> = [
  { name: 'NOP skips a byte', code: [0, 31, 2, 7, 30, 31], output: [7] },
  { name: 'high opcode bits ignored', code: [0xE2, 9, 0xFE, 0xFF], output: [9] },
  { name: 'unsigned JGE taken', code: [2, 200, 4, 1, 11, 10, 2, 0, 30, 31, 30, 31], output: [200] },
  { name: 'unsigned JGE untaken', code: [2, 1, 4, 200, 11, 10, 2, 3, 30, 31, 30, 31], output: [3] },
  { name: 'JEQ taken', code: [2, 7, 4, 7, 10, 10, 2, 0, 30, 31, 30, 31], output: [7] },
  { name: 'JEQ untaken', code: [2, 7, 4, 8, 10, 10, 2, 3, 30, 31, 30, 31], output: [3] },
  { name: 'ADD wraps', code: [2, 255, 4, 1, 6, 30, 31], output: [0] },
  { name: 'SUB wraps', code: [2, 0, 4, 1, 7, 30, 31], output: [255] },
  { name: 'RAM address 32 aliases zero', code: [2, 42, 5, 32, 1, 0, 30, 31], output: [42] },
  { name: 'CALL saves operand PC', code: [14, 4, 30, 31, 2, 9, 15], output: [9] },
  { name: 'moves between A and B', code: [2, 4, 17, 2, 0, 16, 30, 31], output: [4] },
  { name: 'repeated OUT preserved', code: [2, 5, 30, 30, 31], output: [5, 5] },
  { name: 'PC wraps at 256 through NOP', code: [8, 255], output: [] },
];
test.each(probes)('Original ISA edge case: $name', ({ name, code, output }) => {
  const oracle = interpret(code);
  assert.deepEqual(oracle.output_history, output);
  compareProgram(runProgram(oracle), oracle, name);
});
test('source boot loader stops at counter 31 and leaves RAM byte 31 unchanged', () => {
  // READY = en && counter == 31 removes boot write-enable immediately.
  // The preceding edge wrote address 30. This is the original wiring's limit.
  const image = [2, 7, 30, 31, ...new Array<number>(27).fill(0), 0xAB];
  const oracle = interpret(image.slice(0, 31));
  oracle.program_bytes = image;
  const run = runProgram(oracle);
  compareProgram(run, oracle, 'loader terminal count');
  assert.equal(run.bootPulses, 31);
  assert.equal(run.final.ram[31], 0);
});
test('Actual initial reset with both clocks low then original countdown', () => {
  const oracle = programs['countdown']!;
  const run = runProgram(oracle, true);
  assert.deepEqual(run.outputs, [0, ...oracle.output_history]);
  assert.equal(run.final.PC, 12);
  assert.equal(run.final.A, 0);
  assert.equal(run.final.B, 1);
  assert.equal(run.final.SP, 255);
});
test('HALT/reset from original CALLRET, flags retained and program reruns', () => {
  const oracle = programs['callret']!;
  const run = runProgram(oracle);
  const s = run.s;
  const halted = architecture(s);
  assert.equal(halted.cpuClock, 0);
  s.setComponentInput('v116', 'Y', 1);
  s.settle();
  s.setComponentInput('v116', 'Y', 0);
  s.settle();
  const phases: Array<Record<string, unknown>> = [];
  const outputs: number[] = [];
  let restarted = false;
  for (let cycle = 0; cycle < 3000; cycle++) {
    if (s.readNet(rootNet(83, 'ovf')) === 0) {
      restarted = true;
      s.setComponentInput('v84', 'Y', 1);
      s.settle();
      s.setComponentInput('v84', 'Y', 0);
      s.settle();
      phases.push({ cycle, phase: 'boot', ...architecture(s), stable: stable(s) });
      continue;
    }
    const ldOut = s.readNet(rootNet(68, 'LdOut')), oldClock = s.readNet(rootNet(20, 'C'));
    s.setComponentInput('v2', 'Y', 1);
    s.settle();
    const high = architecture(s);
    phases.push({ cycle, phase: 'primary-high', ...high, stable: stable(s) });
    if (ldOut === 1 && oldClock === 0 && high.cpuClock === 1)
      outputs.push(high.OUT as number);
    s.setComponentInput('v2', 'Y', 0);
    s.settle();
    phases.push({ cycle, phase: 'primary-low', ...architecture(s), stable: stable(s) });
    if (restarted && s.readNet(rootNet(68, 'Hlt')) === 1)
      break;
  }
  const final = architecture(s);
  assert(restarted);
  assert.equal(final.Hlt, 1);
  assert.equal(final.A, 10);
  assert.equal(final.PC, 16);
  assert.deepEqual(outputs, [0, ...oracle.output_history]);
  quiet(s);
  for (const phase of phases) {
    const status = phase.stable as ReturnType<typeof stable>;
    assert.equal(status.architectural_unknowns.length, 0);
    assert.equal(status.stable_contention.length, 0);
  }
  const afterClear = phases.find(p => p.A === 0 && p.OUT === 0 && p.boot === 0);
  assert(afterClear);
  assert.deepEqual(afterClear.flags, halted.flags);
  assert.equal((afterClear.ram as number[])[31], halted.ram[31], 'warm loader retains stack byte 31');
});
for (const name of ['callret', 'countdown', 'fib', 'pushpop'])
  test(`Retained oscillators run original ${name} at all instruction boundaries`, () => {
    const oracle = programs[name]!;
    const circuit = structuredClone(faithful);
    circuit.components.find((component) => component.id === 'v82')!.params!.contents = oracle.program_bytes.map((value) => value.toString(16)).join(' ');
    const sim = new Simulator(loadCircuit(circuit), { rateHz: 1000 });
    sim.settle();
    const outputs: Array<number | string> = [];
    const boundaries: Array<ReturnType<typeof architecture>> = [];
    let ticks = 0;
    for (; ticks < 50000; ticks++) {
      const oldClock = sim.readNet(rootNet(20, 'C'));
      const controls = runtimeWord(sim, 'v68__v0', 'D', 29);
      const loadOutput = sim.readNet(rootNet(68, 'LdOut'));
      sim.tick();
      const clock = sim.readNet(rootNet(20, 'C'));
      if (oldClock === 0 && clock === 1) {
        const after = architecture(sim);
        if (loadOutput === 1)
          outputs.push(after.OUT);
        if (typeof controls === 'number' && (controls & 2 ** 20) !== 0)
          boundaries.push(after);
      }
      if (sim.readNet(rootNet(68, 'Hlt')) === 1) {
        boundaries.push(architecture(sim));
        break;
      }
    }
    assert.equal(sim.readNet(rootNet(68, 'Hlt')), 1);
    assert.deepEqual(outputs, oracle.output_history);
    assert.equal(boundaries.length, oracle.instructions.length);
    for (let index = 0; index < boundaries.length; index++) {
      const actual = boundaries[index]!, expected = oracle.instructions[index]!.after;
      for (const [field, key] of [['PC', 'pc'], ['A', 'a'], ['B', 'b'], ['OUT', 'out'], ['SP', 'sp']] as const)
        assert.equal(actual[field], expected[key]);
      assert.deepEqual(actual.flags, expected.flags);
      assert.deepEqual(actual.ram, expected.ram);
      assert.equal(actual.Hlt, expected.halted ? 1 : 0);
    }
    quiet(sim);
    const halted = architecture(sim);
    for (let tick = 0; tick < 50; tick++)
      sim.tick();
    assert.deepEqual(architecture(sim), halted);
  });
