import type { DriverValue, RuntimeGraph } from './ir';
import { LOGIC_NET_STATES, NET_STATES, netStateByte, resolveNet } from './nets';

// Four bits leave room for weak drivers without changing the resolved-net
// encoding. Small stateless built-ins and the bounded DFF state machine
// use truth tables generated by their original evaluators.
export const DRIVER_STATES: readonly DriverValue[] = [0, 1, 'Z', 'X', 'L', 'H', '0Z', '1Z'];

export function driverByte(value: DriverValue): number {
  return typeof value === 'number' ? value : value === 'Z' ? 2 : value === 'X' ? 3 : value === 'L' ? 4 : value === 'H' ? 5 : value === '0Z' ? 6 : 7;
}

// OR-ing the eight driver-presence bits preserves every resolution distinction,
// including conflicting strong values alongside X and conflicting weak pulls.
export const RESOLVED_MASKS = new Uint8Array(256);
for (let mask = 0; mask < 256; mask++) {
  RESOLVED_MASKS[mask] = netStateByte(resolveNet(DRIVER_STATES.filter((_, bit) => mask & (1 << bit))).value);
}
export const RESOLVED_DRIVERS = new Uint8Array([0, 1, 2, 3, 0, 1, 3, 3]);

export function compileTables(graph: RuntimeGraph) {
  const offsets = new Uint32Array(graph.components.length);
  const kinds = new Uint8Array(graph.components.map(comp => comp.evalKind));
  const inputs = new Uint32Array(graph.components.length * 5);
  const inputCounts = new Uint8Array(graph.components.length);
  const proposed = new Uint32Array(graph.components.length);
  const current = new Uint32Array(graph.components.length);
  const arithmetic = new Uint8Array(graph.components.length);
  const outputOffsets = new Uint32Array(graph.components.length + 1);
  const outputNets: number[] = [];
  const initialDrivers: number[] = [];
  for (let c = 0; c < graph.components.length; c++) {
    const comp = graph.components[c]!;
    outputOffsets[c] = outputNets.length;
    outputNets.push(...comp.outputNetIdx);
    initialDrivers.push(...comp.outputBuf.map(driverByte));
    if (comp.outputBuf.length <= 8) {
      for (let pin = 0; pin < comp.outputBuf.length; pin++) current[c]! |= driverByte(comp.outputBuf[pin]!) << (pin * 4);
    }
  }
  outputOffsets[graph.components.length] = outputNets.length;
  const driverOffsets = new Uint32Array(graph.nets.length + 1);
  const drivers: number[] = [];
  const listenerOffsets = new Uint32Array(graph.nets.length + 1);
  const listeners: number[] = [];
  const singleDrivers = new Int32Array(graph.nets.length).fill(-1);
  for (let n = 0; n < graph.nets.length; n++) {
    driverOffsets[n] = drivers.length;
    listenerOffsets[n] = listeners.length;
    listeners.push(...graph.nets[n]!.listenerComps);
    for (const d of graph.nets[n]!.drivers) drivers.push(outputOffsets[d.comp]! + d.outIdx);
    if (graph.nets[n]!.drivers.length === 1) singleDrivers[n] = drivers[driverOffsets[n]!]!;
  }
  driverOffsets[graph.nets.length] = drivers.length;
  listenerOffsets[graph.nets.length] = listeners.length;
  const dffTables = new Map<number, number>();
  const words: number[] = [0]; // zero offset means registry/normal dispatch
  for (let c = 0; c < graph.components.length; c++) {
    const comp = graph.components[c]!;
    const kind = comp.evalKind;
    if (kind === 15 && comp.inputBuf.length > 4 && comp.outputBuf.length <= 8) arithmetic[c] = 1;
    if (kind < 1 || kind > 19 || kind === 10 || comp.inputBuf.length > (kind === 9 ? 5 : 4) || comp.outputBuf.length > 8) continue;
    offsets[c] = words.length;
    inputCounts[c] = comp.inputBuf.length;
    inputs.set(comp.inputNetIdx, c * 5);
    if (kind === 9) {
      const params = comp.params as { enable?: boolean; clrActiveLow?: boolean; preActiveLow?: boolean };
      const dffKey = (params.enable ? 1 : 0) | (params.clrActiveLow ? 2 : 0)
        | (params.preActiveLow ? 4 : 0) | (comp.inputIsLogic[0] ? 8 : 0);
      const cached = dffTables.get(dffKey);
      if (cached !== undefined) { offsets[c] = cached; continue; }
      dffTables.set(dffKey, words.length);
    }
    const ins = [...comp.inputBuf];
    const outs = [...comp.outputBuf];
    for (let vector = 0; vector < 4 ** (ins.length + (kind === 9 ? 2 : 0)); vector++) {
      for (let pin = 0; pin < ins.length; pin++) {
        ins[pin] = (comp.inputIsLogic[pin] ? LOGIC_NET_STATES : NET_STATES)[(vector >>> (pin * 2)) & 3]!;
      }
      const state = kind === 9 ? {
        q: NET_STATES[(vector >>> (ins.length * 2)) & 3]!,
        prevClk: NET_STATES[(vector >>> ((ins.length + 1) * 2)) & 3]!,
      } : comp.state;
      comp.primitive.evaluate(ins, outs, state, comp.params);
      let word = 0;
      for (let pin = 0; pin < outs.length; pin++) word |= DRIVER_STATES.indexOf(outs[pin]!) << (pin * 4);
      words.push(word >>> 0);
    }
  }
  return {
    offsets, kinds, inputs, inputCounts, proposed, current, arithmetic, words: new Uint32Array(words),
    outputOffsets, outputNets: new Uint32Array(outputNets),
    driven: new Uint8Array(initialDrivers), driverOffsets, drivers: new Uint32Array(drivers),
    listenerOffsets, listeners: new Uint32Array(listeners), singleDrivers,
    forced: new Uint8Array(graph.nets.map(net => driverByte(net.forced))),
  };
}

// Preserve the graph's existing mutable inspection buffers without copying
// driver strings on every commit. Hot evaluation/resolution uses only bytes.
export function bindDriverViews(graph: RuntimeGraph, plan: ReturnType<typeof compileTables>): void {
  for (let c = 0; c < graph.components.length; c++) {
    const comp = graph.components[c]!;
    for (let pin = 0; pin < comp.outputBuf.length; pin++) {
      const slot = plan.outputOffsets[c]! + pin;
      Object.defineProperty(comp.outputBuf, pin, {
        enumerable: true, configurable: true,
        get: () => DRIVER_STATES[plan.driven[slot]!]!,
        set: (value: DriverValue) => {
          const byte = driverByte(value);
          plan.driven[slot] = byte;
          if (plan.offsets[c] || plan.arithmetic[c]) plan.current[c] = (plan.current[c]! & ~(15 << (pin * 4))) | (byte << (pin * 4));
        },
      });
    }
  }
  for (let n = 0; n < graph.nets.length; n++) {
    Object.defineProperty(graph.nets[n]!, 'forced', {
      enumerable: true, configurable: true,
      get: () => DRIVER_STATES[plan.forced[n]!]!,
      set: (value: DriverValue) => { plan.forced[n] = driverByte(value); },
    });
  }
}
