import './prof_counters';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import '../src/engine/behavioral/index';
import '../src/engine/primitives/index';
import type { CircuitJSON } from '../src/engine/ir';
import { loadCircuit } from '../src/engine/loader';
import { Simulator } from '../src/engine/sim';
import '../src/stdlib/index';
const here = dirname(fileURLToPath(import.meta.url));
const circuit = JSON.parse(readFileSync(resolve(here,'..','examples','ben_eater_8bit.json'),'utf8')) as CircuitJSON;
const sim = new Simulator(loadCircuit(circuit));
sim.settle();
sim.setComponentInput('sw_reset','Y',1);
sim.settle();
for (let i=0;i<1000;i++) sim.tick();
const { totalIter, totalEval, settleCount } = globalThis as any;
console.log('settles', settleCount, 'iters', totalIter, 'eval', totalEval);
console.log('avg iter per settle', (totalIter/settleCount).toFixed(2), 'avg eval per iter', (totalEval/totalIter).toFixed(2));
